dwsurvey:
  site: 'local'
  web:
    # 后端文件存储目录，默认即在安装包同级目录下
    file-path: /Users/lance/home/dwsurvey/
    # 使用哪种部署模式，后期可能会去掉，可以先保持默认
    static-type: static
    # 站点访问地址，如果配置有域名则为域名地址
    site-url: http://localhost:8081
    # 资源访问地址，便于存储模式的切换，目前可以保持与site-url一样
    resource-url: http://localhost:8080
    # 站点信息配置，会出现在底部footer区
    info:
      # 站点名称
      site-name: 调问网
      # 站点名称，对应的URL地址
      site-url: http://www.diaowen.net
      # 站点备案号
      site-icp: 京ICP备13050030号-3
      # 站点联系人邮箱
      site-mail: service@diaowen.net
      # 站点联系人电话
      site-phone: 18888888888
  # 用于微信集成相关，目前社区版还没未启用。
  weixin:
    app-id: xxx
    app-secret: xxx
    server:
      token: xxx
      encodingAESKey:
  # 产品版本号信息，V5-代表最新的前后端分离版本
  version:
    info: DWSurvey OSS V5.2.6 Boot
    number: OSS V5.2.6
    built: 2022/03/17
  jwt:
    secret: lanceSecretKey
    expiration: 86400000

# 服务占用的端口号
server:
  port: 8080

# Spring相关配置
spring:
  application:
    name: dwsurvey
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${dwsurvey.web.file-path}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dwsurvey?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: li123456
    hikari:
      pool-name: sv-pool
      maximum-pool-size: 200
      minimum-idle: 20
      connection-timeout: 15000
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: net.diaowen.common.plugs.mapper.SnakeCaseNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        cache:
          use_second_level_cache: false
          use_query_cache: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql

logging:
  file:
    name: ${spring.application.name}
    path: logs
  level:
    org.springframework: info
    org.hibernate: ERROR
    org.apache: ERROR
    net.diaowen: debug

