-- --------------------------
SELECT *
from t_an_answer;
SELECT *
from t_an_checkbox;
select *
from t_an_dfillblank;
SELECT *
from t_an_enumqu;
select *
from t_an_fillblank;
SELECT *
from t_an_order;
select *
from t_an_radio;
select *
from t_an_score;
select *
from t_an_uplodfile;
select *
from t_an_yesno;

SELECT *
from t_question;
select *
from t_qu_checkbox;
SELECT *
from t_qu_multi_fillblank;
select *
from t_qu_orderby;
select *
from t_qu_radio;
SELECT *
from t_qu_score;

select *
from t_survey_directory;
SELECT *
from t_survey_detail;
select *
from t_survey_answer;
-- ----------------------------